### PR TITLE
MEC-187 Change search criteria display

### PR DESCRIPTION
**Pull request by bridgetburke**
Updates for MEC-187

- Removes constraints from top of search results across catalog, bib, and quotes
- Restyle search results on the left sidebar, including making them readable for long filters 'Parts of Speech or Origin, e.g.', changing color, icon
- Remove Sort by Results # across catalog, bib, and quotes

Still need to add the search value after results but I think that may need to be best done in a helper?

### CODE REVIEW

**Comment by billdueber** [comment]
I think what we want here is the search text next to the number of results (as you mention) and *not* in the list on the left. Looks like that means we'll have to muck with the constraints code. I'll take a gander.

**Comment by bridgetburke** [comment]
Oh ok, I thought it would be in both places for better visibility.

**Comment by billdueber** [comment]
Try doing this:
```
git co -b contraint-updates-2
git pull origin move_query_constraint
```

...and take a look. I've moved the calls to the constraint code so the query isn't in the sidebar and instead appears next to the sort. It should be moved, I think,  to being _before_ the sort, but I figured I'd just screw it up.

**Comment by billdueber** [comment]
I'm gonna go ahead and merge this, and we'll work on the rest of it as a separate issue.

**Pull request merged**
